### ISSUE TITLE
Corrupted mp4 file on some devices

### ISSUE THREAD

**Issue by sixo** [spaceLenny/recordablesurfaceview#9] opened 2019-01-03 09:41 UTC
I found this library very useful. It was really easy to make it work on Android 7.

However, on one of my devices with Android 6 the recorded file seems to be corrupt. 

I'm using it to record camera frames and apply effects with OpenGL ES 2.0. 
The rendering works as expected. I can see the preview. But when I start recording, the output file is significantly smaller than on the device with Android 7 (which produces a correct output file). I can see that the size of the file is growing, so something seems to be still recorded though.

You set the minSdkVersion of the project to 24, but I was expecting that recording a surface with MediaRecorder should be possible since Lollipop.

Could this be fixed somehow by tweaking the settings in `initRecorder()`? Or is the minSdkVersion 24 necessary? If this is device specific issue, how could I debug this?

Thanks

**Comment by spaceLenny** [comment] 2019-01-03 17:40
minSdkVersion 24 is required. 

For your use case you may want to check out [shadercam from Google Creative Lab](https://github.com/googlecreativelab/shadercam).

**Comment by sixo** [comment] 2019-01-03 17:50
I made it work also on Marshmallow. The issue was completely unrelated to your library. 
Thanks again

**Comment by spaceLenny** [comment] 2019-01-03 18:44
Wow awesome news! I'll try the same and schedule a run thru of our tests. 

If you'd like, could you submit a PR and then you'll be on the contribution list if all goes well.

**Comment by sixo** [comment] 2019-01-03 19:21
I didn't change anything in code. I just plugged it into my app according to your provided instructions.

**Comment by sixo** [comment] 2019-01-07 12:02
I thought I've found the issue,  but I was wrong. 

I mean everything works as expected. Rendering and recording works on Marshmallow without issues. However, after some time recording stops to work (recorded file is corrupted). Rendering works without issues. 

I need to reboot the device and it starts working again (killing my app is not sufficient). 
I cannot find anything relevant in the logs. 

It could be something device specific. Or it could be related to the cleanup. The surface created in `doSetup()` with `createPersistentInputSurface()` is not always released properly (The app is in early stage of development and it crashes or is killed by ADB regularly).

**Comment by spaceLenny** [comment] 2019-01-07 18:45
What device are you seeing this behavior on? Also, is this in <= sdk v23

**Comment by sixo** [comment] 2019-01-10 21:07
For now this only happened on one Lenovo device with Marshmallow.

**Comment by drewbuckley** [comment] 2019-01-19 05:00
Rather than post a new issue, i too have the same issue.

Record creates the file but it's not playable.

I'm using Android Pie. Not sure if this library is ok for 28?

**Comment by spaceLenny** [comment] 2019-01-19 05:40
Can you give me a logcat and device info? 

I'm unable to reproduce on hardware I have available.

It is tested and supported on Pie, so there must be something missing.  Are you calling stop when completed?

**Comment by drewbuckley** [comment] 2019-01-19 06:30
2019-01-19 17:23:00.888 13599-14308/? E/MPEG4Writer: The number of recorded samples is 0
2019-01-19 17:23:00.888 13599-14308/? E/MPEG4Writer: Dumping Video track's last 10 frames timestamp and frame type 
2019-01-19 17:23:00.888 13599-14308/? W/MPEG4Writer: 0-duration samples found: 1
2019-01-19 17:23:00.888 13599-14308/? W/MPEG4Writer: 0-duration samples found: 1
2019-01-19 17:23:00.888 13599-14308/? I/MPEG4Writer: Received total/0-length (1/0) buffers and encoded 0 frames. - Video
2019-01-19 17:23:00.886 14299-14299/? I/VideoEncMsgThre: type=1400 audit(0.0:2896): avc: denied { ioctl } for path="/dev/msm_vidc_enc" dev="tmpfs" ino=7708 ioctlcmd=10 scontext=u:r:mediacodec:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
2019-01-19 17:23:00.920 364-9975/? E/OMX-VENC: (4683) - 
     Destroy C2D instance
2019-01-19 17:23:00.926 13599-14225/? I/MediaCodecSource: encoder (video) stopped
2019-01-19 17:23:00.926 13599-13645/? D/MPEG4Writer: Video track source stopped
2019-01-19 17:23:00.926 13599-13645/? D/MPEG4Writer: Video track stopped. Stop source
2019-01-19 17:23:00.926 13599-13645/? D/MPEG4Writer: Audio track stopping. Stop source
2019-01-19 17:23:00.926 13599-13645/? D/MPEG4Writer: Audio track source stopping
2019-01-19 17:23:00.927 13599-14225/? I/MediaCodecSource: encoder (audio) stopping
2019-01-19 17:23:00.927 13599-14225/? I/MediaCodecSource: encoder (audio) already stopped
2019-01-19 17:23:00.927 13599-13645/? D/MPEG4Writer: Audio track source stopped
2019-01-19 17:23:00.927 13599-13645/? D/MPEG4Writer: Audio track stopped. Stop source
2019-01-19 17:23:00.927 13599-13645/? D/MPEG4Writer: Duration from tracks range is [0, 31903494] us
2019-01-19 17:23:00.927 13599-13645/? D/MPEG4Writer: Stopping writer thread
2019-01-19 17:23:00.927 13599-14307/? D/MPEG4Writer: 0 chunks are written in the last batch
2019-01-19 17:23:00.929 13599-13645/? D/MPEG4Writer: Writer thread stopped
2019-01-19 17:23:00.929 13599-13645/? D/MPEG4Writer: Video track stopping. Stop source
2019-01-19 17:23:00.929 13599-13645/? D/MPEG4Writer: Audio track stopping. Stop source
2019-01-19 17:23:00.943 308-14303/? D/audio_hw_primary: in_standby: enter: stream (0xa81b22a0) usecase(7: audio-record)
2019-01-19 17:23:00.980 308-14303/? D/audio_hw_primary: in_set_parameters: enter: kvpairs=routing=0
2019-01-19 17:23:00.988 308-308/? D/audio_hw_primary: adev_close_input_stream: enter:stream_handle(0xa81b22a0)
2019-01-19 17:23:00.988 308-308/? D/audio_hw_primary: in_standby: enter: stream (0xa81b22a0) usecase(7: audio-record)

**Comment by drewbuckley** [comment] 2019-01-19 06:42
Device info is Samsung Galaxy S4 rooted running Pie rom

**Comment by spaceLenny** [comment] 2019-01-19 06:54
Is this for all recordings or just long recordings?

**Comment by drewbuckley** [comment] 2019-01-19 07:01
Yes for all recording no matter how long. I just noted that the filer does get larger when run longer but still can't play it.

**Comment by drewbuckley** [comment] 2019-01-19 07:02
Still a lot smaller than when i was using MediaRecorder with MediaProjection which was ok.

**Comment by spaceLenny** [comment] 2019-01-19 07:03
One last question: can you run the example app and let me know if the same behavior happens there?

**Comment by drewbuckley** [comment] 2019-01-19 07:08
OK. let me try it and post back

**Comment by drewbuckley** [comment] 2019-01-19 07:43
Not sure where it's writing the mp4 too? can't find captures on the phone.

**Comment by spaceLenny** [comment] 2019-01-19 15:43
When you click stop in the menu, it should show you a share sheet where you can email the file to yourself, for example.

**Comment by drewbuckley** [comment] 2019-01-19 21:14
I really need to read pop ups before i cancel them.
Yes that works.
I'll trace the code back to see what i'm doing wrong in my app. thanks. Great idea and well done.

**Comment by spaceLenny** [comment] 2019-01-19 22:40
Hm from the logcat it seems that you're directly accessing media recorder and it's state is the error. 

I suggest you check out the MediaRecorder docs (linked in the readme) if you plan on doing this.

As for your initial error, it's likely that a long video will take some time to encode and finalize. You may want to try calling stopRecording on a background thread.

**Comment by Cotel** [comment] 2019-03-05 08:49
Hello there! I'm also having the same issue with several devices 😅 I'm not using this lib but came here through `https://github.com/googlecreativelab/shadercam`. I tried using the new renderers which use this library but I'm still having this issue.

In my case when videos are recorded they generate a mp4 file which usually is 9-8 min long with the first photogram still until the last second of the video, then it moves 2 or 3 photograms and then ends.

I've been able to reproduce this issue with the following devices:

- Razer phone (android ver. 8.1)
- One plus one 6 (android ver. 9)
- Huawei mate p20 lite (android ver. 8.1)
- Huawei p20 pro (several android versions)
- Samsung s9 note (android ver. unknown)

Thank you for your work! 👍

**Comment by kartik1225** [comment] 2019-03-31 15:54
I am also having the same issue. 
Device info:
 - Onplus 5t (android 9)
How do I resolve it? having corrupted mp4 files.

**Comment by spaceLenny** [comment] 2019-03-31 16:22
Could you try running the demo app and confirm it's not working as well? Also, checking the codec capabilities of the MediaRecorder on that device would be helpful

**Comment by kartik1225** [comment] 2019-03-31 16:52
yes, I have tried the sample app is working perfectly on my device. but somehow I am getting corrupted video file on my app.

Basically, I want to export a video from [lottie](https://github.com/airbnb/lottie-android) animation view (an animation library).
here is my code:
I am initiating the `RecordableSurfaceView`like this as told in the readme.
```
surfaceView.setRendererCallbacks(this);
surfaceView.doSetup();
holder = surfaceView.getHolder();
```
then when the animation starts from the Lottie animation view I am listing that animation update callback and then generating bitmaps and updating in the RecordableSurfaceView canvas.

_this function invoke in every frame so basically it's mirroring everything in the RecordableSurfaceView_
```
animationView.addAnimatorUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator valueAnimator) {
                    FrameLayout view = frameLayout;
                    Bitmap bitmap = Bitmap.createBitmap(view.getWidth(), view.getHeight(), Bitmap.Config.ARGB_8888);
                    Canvas canvas = new Canvas(bitmap);
                    view.draw(canvas);
                    bmp = bitmap;
            }
        });
```
_this is the draw function for updating canvas for surface view_
```
public void draw() {
        holder.lockCanvas();
        if(bmp != null){
            canvas.drawBitmap(bmp,0,0,null);
        }
        canvas.save();
        holder.unlockCanvasAndPost(canvas);
    }
```

_this function starts recording when Lottie animation starts and ends when the animation ends_
```
     animationView.addAnimatorListener(new Animator.AnimatorListener() {
            @Override
            public void onAnimationStart(Animator animator) {
                File folder =  new File(Environment.getExternalStorageDirectory().getAbsolutePath()+"/temp/");
                folder.mkdirs();
                File imageFolder =  new File(Environment.getExternalStorageDirectory().getAbsolutePath()+"/temp/" + String.valueOf(new Date()) +".mp4");
                try {
                   surfaceView.initRecorder(imageFolder,surfaceView.getWidth(),surfaceView.getHeight(),null,null);
                    isRecording = surfaceView.startRecording();
                    Log.i(tag, "onAnimationStart: " + isRecording);
                } catch (IOException e) {
                    Log.i(tag, "onAnimationStart: work" + e.getMessage());
                    e.printStackTrace();
                }
            }

            @Override
            public void onAnimationEnd(Animator animator) {
                Log.i(tag, "onAnimationEnd: " + isRecording);
                if(isRecording){
                    surfaceView.stopRecording();
                    isRecording = false;
                    Log.i(tag, "onAnimationEnd: " + "stoped");
                }
            }

            @Override
            public void onAnimationCancel(Animator animator) {

            }

            @Override
            public void onAnimationRepeat(Animator animator) {

            }
        });
```
Everything is going fine but in the result, I am getting corrupted mp4.
Please navigate me what I am doing wrong!

thank you  😊

**Comment by spaceLenny** [comment] 2019-03-31 16:56
This library is designed for opengl es rendering not canvas rendering.

**Comment by afsaredrisy** [comment] 2020-09-27 05:03
I am also having the same issue with Realme deices. I installed the provided sample application and did not change a bit in code. 
While recording after that It shared file to external intent their found corrupt mp4. Is there any workaround to resolve this?

**Comment by afsaredrisy** [comment] 2020-09-28 02:26
I fixed it by changing the video encoder from default to H264. 
mediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.H264);
Its working fine now.

**Comment by spaceLenny** [comment] 2021-08-23 04:38
Closing as there seems to be a workaround

**Closed** 2021-08-23 04:38 UTC

**Comment by thirumoorthi-n-4386** [comment] 2023-04-26 12:51
Output mp4 video corrupted for Samsung note devices, it is running on Android 12.  Any solution for this?
Using aac format for audio default format for video.
